import { supabase } from './supabase';
import { Report } from '../types';

/**
 * reportService.ts
  *
   * Stage 2A changes:
    *  - fetchReportsFromSupabase() now accepts a userId parameter and applies an
     *    explicit .eq('created_by', userId) filter in addition to RLS.
      *  - mergeSupabaseReportsToLocal() is kept for backward compatibility but is
       *    no longer called from Dashboard or MyReports (replaced by useReports hook).
        *  - syncReportToSupabase() is unchanged (still used as fire-and-forget from saveReport).
         *  - getMyOrgId() is removed - organisation_id is now loaded at login via authContext.
          */

          const STORAGE_KEY = 'sitk_reports';

          function stripPhotos(report: Report): Report {
            return { ...report, photos: [] };
            }

            function toSupabasePayload(report: Report, organisationId: string | null) {
              const { id, title, type, status, location, date, authorId, description, photos, ...rest } = report as any;
                const reportRow: Record<string, any> = {
                    id,
                        title,
                            type: type || null,
                                status,
                                    location: location || null,
                                        date: date || null,
                                            created_by: authorId || null,
                                                description: description || null,
                                                  };
                                                    if (organisationId) {
                                                        reportRow.organisation_id = organisationId;
                                                          }
                                                            const formPayload = {
                                                                ...rest,
                                                                    photos: photos ? photos.map((p: any) => ({ ...p, dataUrl: '' })) : [],
                                                                      };
                                                                        return { reportRow, formPayload };
                                                                        }

                                                                        export async function syncReportToSupabase(report: Report): Promise<void> {
                                                                          try {
                                                                              const { data: { session } } = await supabase.auth.getSession();
                                                                                  if (!session) return;
                                                                                      // organisation_id will be null here (sync called from saveReport which has no org context yet)
                                                                                          // Stage 2B will fix this by passing orgId from the caller
                                                                                              const orgId: string | null = null;
                                                                                                  const { reportRow, formPayload } = toSupabasePayload(report, orgId);
                                                                                                      const { error: reportError } = await supabase
                                                                                                            .from('reports')
                                                                                                                  .upsert(reportRow, { onConflict: 'id' });
                                                                                                                      if (reportError) { console.warn('[reportService] upsert report:', reportError.message); return; }
                                                                                                                          const { error: dataError } = await supabase
                                                                                                                                .from('report_data')
                                                                                                                                      .upsert({ report_id: reportRow.id, form_data: formPayload }, { onConflict: 'report_id' });
                                                                                                                                          if (dataError) { console.warn('[reportService] upsert report_data:', dataError.message); return; }
                                                                                                                                              console.log('[reportService] Synced to Supabase:', reportRow.id);
                                                                                                                                                } catch (err) {
                                                                                                                                                    console.warn('[reportService] sync error (non-fatal):', err);
                                                                                                                                                      }
                                                                                                                                                      }

                                                                                                                                                      /**
                                                                                                                                                       * Fetch saved reports from Supabase for a specific user.
                                                                                                                                                        * Applies an explicit created_by filter in addition to RLS.
                                                                                                                                                         * Returns [] on any error so callers can fall back to localStorage cache.
                                                                                                                                                          */
                                                                                                                                                          export async function fetchReportsFromSupabase(userId: string): Promise<Report[]> {
                                                                                                                                                            try {
                                                                                                                                                                const { data: { session } } = await supabase.auth.getSession();
                                                                                                                                                                    if (!session) return [];
                                                                                                                                                                        const { data, error } = await supabase
                                                                                                                                                                              .from('reports')
                                                                                                                                                                                    .select('id, title, type, status, location, date, description, created_by, report_data ( form_data )')
                                                                                                                                                                                          .eq('created_by', userId)
                                                                                                                                                                                                .order('created_at', { ascending: false });
                                                                                                                                                                                                    if (error) { console.warn('[reportService] fetch:', error.message); return []; }
                                                                                                                                                                                                        return (data || []).map((row: any) => {
                                                                                                                                                                                                              const formData = row.report_data?.form_data ?? {};
                                                                                                                                                                                                                    return {
                                                                                                                                                                                                                            id: row.id,
                                                                                                                                                                                                                                    title: row.title,
                                                                                                                                                                                                                                            type: row.type,
                                                                                                                                                                                                                                                    status: row.status,
                                                                                                                                                                                                                                                            location: row.location || '',
                                                                                                                                                                                                                                                                    date: row.date || '',
                                                                                                                                                                                                                                                                            authorId: row.created_by || '',
                                                                                                                                                                                                                                                                                    description: row.description || '',
                                                                                                                                                                                                                                                                                            ...formData,
                                                                                                                                                                                                                                                                                                  } as Report;
                                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                                        } catch (err) {
                                                                                                                                                                                                                                                                                                            console.warn('[reportService] fetch error (non-fatal):', err);
                                                                                                                                                                                                                                                                                                                return [];
                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                  /**
                                                                                                                                                                                                                                                                                                                   * @deprecated No longer called from Dashboard or MyReports.
                                                                                                                                                                                                                                                                                                                    * Kept for backward compatibility during the Stage 2A transition.
                                                                                                                                                                                                                                                                                                                     * Will be removed in a subsequent cleanup pass.
                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                       * Fetch reports from Supabase and merge into localStorage.
                                                                                                                                                                                                                                                                                                                        * Server records are upserted into the local store (server wins on conflict).
                                                                                                                                                                                                                                                                                                                         * Dispatches 'reportsUpdated' so components refresh automatically.
                                                                                                                                                                                                                                                                                                                          */
                                                                                                                                                                                                                                                                                                                          export async function mergeSupabaseReportsToLocal(): Promise<void> {
                                                                                                                                                                                                                                                                                                                            try {
                                                                                                                                                                                                                                                                                                                                const { data: { session } } = await supabase.auth.getSession();
                                                                                                                                                                                                                                                                                                                                    if (!session) return;
                                                                                                                                                                                                                                                                                                                                        const serverReports = await fetchReportsFromSupabase(session.user.id);
                                                                                                                                                                                                                                                                                                                                            if (serverReports.length === 0) return;
                                                                                                                                                                                                                                                                                                                                                const raw = localStorage.getItem(STORAGE_KEY);
                                                                                                                                                                                                                                                                                                                                                    const local: Report[] = raw ? JSON.parse(raw) : [];
                                                                                                                                                                                                                                                                                                                                                        const localMap = new Map(local.map((r: Report) => [r.id, r]));
                                                                                                                                                                                                                                                                                                                                                            for (const serverReport of serverReports) {
                                                                                                                                                                                                                                                                                                                                                                  const existing = localMap.get(serverReport.id);
                                                                                                                                                                                                                                                                                                                                                                        if (existing) {
                                                                                                                                                                                                                                                                                                                                                                                localMap.set(serverReport.id, {
                                                                                                                                                                                                                                                                                                                                                                                          ...serverReport,
                                                                                                                                                                                                                                                                                                                                                                                                    photos: (existing as any).photos || [],
                                                                                                                                                                                                                                                                                                                                                                                                              savedAt: (existing as any).savedAt || serverReport.date,
                                                                                                                                                                                                                                                                                                                                                                                                                      } as any);
                                                                                                                                                                                                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                    localMap.set(serverReport.id, serverReport);
                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                  const merged = Array.from(localMap.values());
                                                                                                                                                                                                                                                                                                                                                                                                                                                      localStorage.setItem(STORAGE_KEY, JSON.stringify(merged));
                                                                                                                                                                                                                                                                                                                                                                                                                                                          window.dispatchEvent(new Event('reportsUpdated'));
                                                                                                                                                                                                                                                                                                                                                                                                                                                              console.log('[reportService] Merged', serverReports.length, 'reports from Supabase');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    console.warn('[reportService] mergeSupabaseReportsToLocal error (non-fatal):', err);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                      export async function softDeleteReportInSupabase(id: string): Promise<void> {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const { data: { session } } = await supabase.auth.getSession();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (!session) return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await supabase.from('reports').update({ status: 'Deleted' }).eq('id', id);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          console.warn('[reportService] softDelete error (non-fatal):', err);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            